<?php

namespace App\Filament\Resources;

use App\Filament\Resources\OrderResource\Pages;
use App\Models\Order;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Support\Enums\FontFamily;
use Filament\Tables;
use Filament\Tables\Table;

/**
 * ADMIN Filament resource for orders. Read-mostly: the only mutable
 * control is the status Select. A "manual refund" is simply setting status to
 * `refunded` and saving — no payment/refund integration, no gateway call.
 *
 * NOT the API `OrderResource` under app/Http/Resources.
 */
class OrderResource extends Resource
{
    protected static ?string $model = Order::class;

    protected static ?string $navigationIcon = 'heroicon-o-shopping-bag';

    protected static ?string $navigationGroup = 'Sales';

    protected static ?int $navigationSort = 1;

    protected static ?string $recordTitleAttribute = 'provider_reference';

    /** @var array<string, string> */
    protected static array $statuses = [
        Order::STATUS_PENDING => 'Pending',
        Order::STATUS_PAID => 'Paid',
        Order::STATUS_FAILED => 'Failed',
        Order::STATUS_REFUNDED => 'Refunded',
    ];

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Order')
                    ->columns(2)
                    ->schema([
                        // The one mutable control — admin sets the lifecycle status.
                        // Changing to `refunded` here IS the manual refund path.
                        Forms\Components\Select::make('status')
                            ->options(self::$statuses)
                            ->required()
                            ->native(false)
                            ->helperText('Set to "Refunded" to manually mark a refund — no gateway call is made.'),

                        Forms\Components\TextInput::make('amount_cents')
                            ->label('Amount')
                            ->disabled()
                            ->formatStateUsing(fn (?int $state): ?string => $state === null ? null : '$'.number_format($state / 100, 2)),

                        Forms\Components\TextInput::make('user.name')->label('Buyer')->disabled(),
                        Forms\Components\TextInput::make('product.title')->label('Product')->disabled(),

                        Forms\Components\TextInput::make('provider_reference')->disabled(),
                        Forms\Components\TextInput::make('provider_payment_id')->label('Provider payment id')->disabled(),
                    ]),

                Forms\Components\Section::make('Fulfillment')
                    ->description('Set automatically when payment is confirmed (FulfillOrder) — read-only here. Licenses are generated by fulfillment, never in admin.')
                    ->columns(2)
                    ->schema([
                        // Read-only fulfillment state. Disabled fields are never written back
                        // (Filament excludes disabled fields from the save payload).
                        Forms\Components\TextInput::make('license_key')
                            ->disabled()
                            ->placeholder('Not fulfilled yet')
                            ->prefixIcon('heroicon-m-key')
                            // Mono so the XXXX-XXXX-XXXX-XXXX license reads cleanly (UI system).
                            ->extraInputAttributes(['style' => 'font-family: ui-monospace, SFMono-Regular, Menlo, monospace;']),

                        Forms\Components\TextInput::make('download_count')
                            ->disabled()
                            ->numeric()
                            ->placeholder('0'),

                        Forms\Components\DateTimePicker::make('delivered_at')
                            ->disabled()
                            ->placeholder('Not delivered yet'),

                        Forms\Components\TextInput::make('currency')->disabled(),
                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('id')->sortable(),
                Tables\Columns\TextColumn::make('user.name')->label('Buyer')->searchable()->sortable(),
                Tables\Columns\TextColumn::make('product.title')->label('Product')->searchable()->limit(30),
                Tables\Columns\TextColumn::make('amount_cents')->label('Amount')->money('USD', divideBy: 100)->sortable(),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        Order::STATUS_PAID => 'success',
                        Order::STATUS_FAILED => 'danger',
                        Order::STATUS_REFUNDED => 'warning',
                        default => 'gray',
                    })
                    ->sortable(),
                Tables\Columns\TextColumn::make('provider_reference')->searchable()->limit(24)->toggleable(),
                // Fulfillment at a glance. license_key is copyable (admins often paste it into a
                // manual email) and hidden by default to keep the default list uncluttered.
                Tables\Columns\TextColumn::make('license_key')
                    ->placeholder('—')
                    ->copyable()
                    ->fontFamily(FontFamily::Mono)
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('download_count')->numeric()->sortable()->placeholder('0')->toggleable(),
                Tables\Columns\TextColumn::make('delivered_at')->dateTime()->sortable()->placeholder('Not delivered')->toggleable(),
                Tables\Columns\TextColumn::make('created_at')->dateTime()->sortable()->toggleable(isToggledHiddenByDefault: true),
            ])
            ->defaultSort('created_at', 'desc')
            ->emptyStateIcon('heroicon-o-shopping-bag')
            ->emptyStateHeading('No orders yet')
            ->emptyStateDescription('Orders appear here once a buyer completes checkout.')
            ->filters([
                Tables\Filters\SelectFilter::make('status')->options(self::$statuses),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [];
    }

    public static function getPages(): array
    {
        // No create page — orders originate from checkout, never the admin.
        return [
            'index' => Pages\ListOrders::route('/'),
            'edit' => Pages\EditOrder::route('/{record}/edit'),
        ];
    }
}
